#!/usr/bin/env python3
"""Generate OBJ placeholder meshes for FF7 characters and enemies.

Coordinate system: Z-up (Unreal-native), Y is forward.
Units: centimeters (UE default scale on OBJ import).

Usage:
  python tools/generate_meshes.py                # generate all known recipes
  python tools/generate_meshes.py Cloud          # generate one
"""

from __future__ import annotations

import math
import os
import sys
from dataclasses import dataclass, field
from typing import Callable


# ---------- mesh primitives ---------- #

@dataclass
class Mesh:
    verts: list = field(default_factory=list)   # list[tuple[float, float, float]]
    faces: list = field(default_factory=list)   # list[tuple[int, ...]], 0-based

    def v(self, x: float, y: float, z: float) -> int:
        idx = len(self.verts)
        self.verts.append((x, y, z))
        return idx

    def tri(self, a: int, b: int, c: int) -> None:
        self.faces.append((a, b, c))

    def quad(self, a: int, b: int, c: int, d: int) -> None:
        # Split quad to 2 triangles, same CCW winding.
        self.faces.append((a, b, c))
        self.faces.append((a, c, d))

    def merge(self, other: "Mesh") -> None:
        offset = len(self.verts)
        self.verts.extend(other.verts)
        for f in other.faces:
            self.faces.append(tuple(i + offset for i in f))

    def bounds(self):
        xs = [v[0] for v in self.verts]
        ys = [v[1] for v in self.verts]
        zs = [v[2] for v in self.verts]
        return (min(xs), min(ys), min(zs)), (max(xs), max(ys), max(zs))

    def write_obj(self, path: str, object_name: str) -> None:
        os.makedirs(os.path.dirname(path), exist_ok=True)
        with open(path, "w", encoding="utf-8") as fh:
            fh.write("# Generated by tools/generate_meshes.py\n")
            fh.write(f"o {object_name}\n")
            for x, y, z in self.verts:
                fh.write(f"v {x:.4f} {y:.4f} {z:.4f}\n")
            for face in self.faces:
                fh.write("f " + " ".join(str(i + 1) for i in face) + "\n")


def cuboid(cx: float, cy: float, cz: float, sx: float, sy: float, sz: float) -> Mesh:
    """Axis-aligned box centered at (cx, cy, cz) with full-extents (sx, sy, sz)."""
    m = Mesh()
    hx, hy, hz = sx / 2, sy / 2, sz / 2
    # 8 corners, indexed by (x, y, z) sign pattern
    v000 = m.v(cx - hx, cy - hy, cz - hz)
    v100 = m.v(cx + hx, cy - hy, cz - hz)
    v110 = m.v(cx + hx, cy + hy, cz - hz)
    v010 = m.v(cx - hx, cy + hy, cz - hz)
    v001 = m.v(cx - hx, cy - hy, cz + hz)
    v101 = m.v(cx + hx, cy - hy, cz + hz)
    v111 = m.v(cx + hx, cy + hy, cz + hz)
    v011 = m.v(cx - hx, cy + hy, cz + hz)
    # Quads, CCW when viewed from outside along the face normal.
    m.quad(v000, v010, v110, v100)  # -Z (bottom)
    m.quad(v001, v101, v111, v011)  # +Z (top)
    m.quad(v000, v001, v011, v010)  # -X
    m.quad(v100, v110, v111, v101)  # +X
    m.quad(v000, v100, v101, v001)  # -Y
    m.quad(v010, v011, v111, v110)  # +Y
    return m


def cylinder_z(cx: float, cy: float, z_base: float, z_top: float,
               r: float, segments: int = 16) -> Mesh:
    """Cylinder with axis along +Z, between z_base and z_top."""
    m = Mesh()
    base_ring = []
    top_ring = []
    for s in range(segments):
        theta = 2 * math.pi * s / segments
        x = r * math.cos(theta)
        y = r * math.sin(theta)
        base_ring.append(m.v(cx + x, cy + y, z_base))
        top_ring.append(m.v(cx + x, cy + y, z_top))
    for s in range(segments):
        a = base_ring[s]
        b = base_ring[(s + 1) % segments]
        c = top_ring[(s + 1) % segments]
        d = top_ring[s]
        m.quad(a, b, c, d)
    # Base cap (normal -Z)
    bc = m.v(cx, cy, z_base)
    for s in range(segments):
        a = base_ring[s]
        b = base_ring[(s + 1) % segments]
        m.tri(bc, b, a)
    # Top cap (normal +Z)
    tc = m.v(cx, cy, z_top)
    for s in range(segments):
        a = top_ring[s]
        b = top_ring[(s + 1) % segments]
        m.tri(tc, a, b)
    return m


def uv_sphere(cx: float, cy: float, cz: float, r: float,
              segments: int = 16, rings: int = 10) -> Mesh:
    """UV sphere centered at (cx, cy, cz). Axis: Z-up."""
    m = Mesh()
    top_pole = m.v(cx, cy, cz + r)
    ring_verts = []
    for ri in range(1, rings):
        phi = math.pi * ri / rings  # 0 at top, pi at bottom
        z = r * math.cos(phi)
        ring_r = r * math.sin(phi)
        row = []
        for s in range(segments):
            theta = 2 * math.pi * s / segments
            x = ring_r * math.cos(theta)
            y = ring_r * math.sin(theta)
            row.append(m.v(cx + x, cy + y, cz + z))
        ring_verts.append(row)
    bot_pole = m.v(cx, cy, cz - r)

    first = ring_verts[0]
    for s in range(segments):
        a = first[s]
        b = first[(s + 1) % segments]
        m.tri(top_pole, a, b)
    for ri in range(len(ring_verts) - 1):
        cur = ring_verts[ri]
        nxt = ring_verts[ri + 1]
        for s in range(segments):
            a = cur[s]
            b = cur[(s + 1) % segments]
            c = nxt[(s + 1) % segments]
            d = nxt[s]
            # Reverse winding so outward-normal is consistent with the +Z-up,
            # CCW-outside convention used by the cuboid / cylinder primitives.
            m.quad(a, d, c, b)
    last = ring_verts[-1]
    for s in range(segments):
        a = last[s]
        b = last[(s + 1) % segments]
        m.tri(bot_pole, b, a)
    return m


# ---------- humanoid recipe ---------- #

@dataclass
class HumanoidRecipe:
    """All measurements in cm. Z-up; character faces +Y."""
    total_height: float = 180.0
    head_radius: float = 12.0
    neck_radius: float = 6.0
    neck_height: float = 8.0
    torso_size: tuple = (36.0, 24.0, 52.0)   # width, depth, height
    torso_top_z: float = 154.0
    hip_size: tuple = (30.0, 20.0, 12.0)
    hip_top_z: float = 102.0
    arm_radius: float = 5.0
    arm_offset_x: float = 23.0
    arm_top_z: float = 150.0
    arm_bottom_z: float = 90.0
    leg_radius: float = 8.0
    leg_offset_x: float = 8.0
    leg_top_z: float = 90.0


def build_humanoid(recipe: HumanoidRecipe) -> Mesh:
    m = Mesh()
    r = recipe

    # Head (sphere). Center it just above the neck.
    head_cz = r.torso_top_z + r.neck_height + r.head_radius
    m.merge(uv_sphere(0, 0, head_cz, r.head_radius, segments=20, rings=12))

    # Direction indicator (nose) poking out +Y from head center
    m.merge(cuboid(0, r.head_radius + 2, head_cz, 5, 6, 4))

    # Neck
    m.merge(cylinder_z(0, 0, r.torso_top_z, r.torso_top_z + r.neck_height,
                       r.neck_radius, segments=16))

    # Torso
    torso_cz = r.torso_top_z - r.torso_size[2] / 2
    m.merge(cuboid(0, 0, torso_cz, *r.torso_size))

    # Hips
    hip_cz = r.hip_top_z - r.hip_size[2] / 2
    m.merge(cuboid(0, 0, hip_cz, *r.hip_size))

    # Arms
    m.merge(cylinder_z(-r.arm_offset_x, 0, r.arm_bottom_z, r.arm_top_z,
                       r.arm_radius, segments=12))
    m.merge(cylinder_z(+r.arm_offset_x, 0, r.arm_bottom_z, r.arm_top_z,
                       r.arm_radius, segments=12))

    # Legs (feet at z=0)
    m.merge(cylinder_z(-r.leg_offset_x, 0, 0, r.leg_top_z,
                       r.leg_radius, segments=12))
    m.merge(cylinder_z(+r.leg_offset_x, 0, 0, r.leg_top_z,
                       r.leg_radius, segments=12))

    return m


# ---------- non-humanoid builders ---------- #

def build_redxiii() -> Mesh:
    """Quadruped: long body along +Y, four legs, head forward, tail up-back."""
    m = Mesh()
    body_len = 110.0
    body_w = 32.0
    body_h = 38.0
    body_cz = 52.0   # body center Z (leg_top + body_h / 2)
    leg_top = body_cz - body_h / 2
    # Body
    m.merge(cuboid(0.0, 0.0, body_cz, body_w, body_len, body_h))
    # Head at +Y end, direction indicator (+Y nose)
    head_cy = body_len / 2 + 18.0
    head_cz = body_cz + 8.0
    m.merge(uv_sphere(0.0, head_cy, head_cz, 18.0, segments=16, rings=10))
    m.merge(cuboid(0.0, head_cy + 18.0, head_cz, 4.0, 8.0, 4.0))  # nose
    # 4 legs
    leg_r = 6.0
    for dx, dy in [(-12.0, -38.0), (12.0, -38.0), (-12.0, 38.0), (12.0, 38.0)]:
        m.merge(cylinder_z(dx, dy, 0.0, leg_top, leg_r, segments=10))
    # Tail (back, up)
    m.merge(cylinder_z(0.0, -body_len / 2 - 8.0, body_cz, body_cz + 44.0, 4.0, segments=8))
    return m


def build_caitsith() -> Mesh:
    """Small cat perched atop a stubby moogle body. Two stacked silhouettes."""
    m = Mesh()
    # Moogle body (big sphere, short legs)
    moogle_cz = 55.0
    m.merge(uv_sphere(0.0, 0.0, moogle_cz, 32.0, segments=18, rings=12))
    # Stubby legs
    for dx in (-12.0, 12.0):
        m.merge(cylinder_z(dx, 0.0, 0.0, 28.0, 6.0, segments=10))
    # Side arms (short nubs)
    for dx in (-34.0, 34.0):
        m.merge(cylinder_z(dx, 0.0, 48.0, 68.0, 4.0, segments=8))
    # Cat body on top
    cat_cz = moogle_cz + 40.0
    m.merge(uv_sphere(0.0, 0.0, cat_cz, 18.0, segments=14, rings=10))
    # Cat head
    head_cz = cat_cz + 22.0
    m.merge(uv_sphere(0.0, 0.0, head_cz, 12.0, segments=12, rings=8))
    # Ears
    for dx in (-6.0, 6.0):
        m.merge(cuboid(dx, 0.0, head_cz + 10.0, 4.0, 4.0, 8.0))
    # Direction indicator (+Y nose on cat head)
    m.merge(cuboid(0.0, 13.0, head_cz, 3.0, 4.0, 3.0))
    return m


# ---------- recipes ---------- #

def _tall_humanoid(height_mul: float, width_mul: float = 1.0) -> HumanoidRecipe:
    """Helper: scale a base humanoid by percentages for silhouette distinction."""
    base = HumanoidRecipe()
    s = height_mul
    w = width_mul
    return HumanoidRecipe(
        total_height=base.total_height * s,
        head_radius=base.head_radius * s,
        neck_radius=base.neck_radius * s,
        neck_height=base.neck_height * s,
        torso_size=(base.torso_size[0] * w, base.torso_size[1] * w, base.torso_size[2] * s),
        torso_top_z=base.torso_top_z * s,
        hip_size=(base.hip_size[0] * w, base.hip_size[1] * w, base.hip_size[2] * s),
        hip_top_z=base.hip_top_z * s,
        arm_radius=base.arm_radius * w,
        arm_offset_x=base.arm_offset_x * w,
        arm_top_z=base.arm_top_z * s,
        arm_bottom_z=base.arm_bottom_z * s,
        leg_radius=base.leg_radius * w,
        leg_offset_x=base.leg_offset_x * w,
        leg_top_z=base.leg_top_z * s,
    )


RECIPES: dict[str, Callable[[], Mesh]] = {
    "Cloud":    lambda: build_humanoid(HumanoidRecipe()),
    "Barret":   lambda: build_humanoid(_tall_humanoid(1.10, 1.25)),   # tall, broad
    "Tifa":     lambda: build_humanoid(_tall_humanoid(0.93, 0.90)),   # slim, athletic
    "Aerith":   lambda: build_humanoid(_tall_humanoid(0.92, 0.85)),   # slim
    "RedXIII":  build_redxiii,                                        # quadruped
    "Yuffie":   lambda: build_humanoid(_tall_humanoid(0.88, 0.85)),   # shortest humanoid
    "CaitSith": build_caitsith,                                       # stacked
    "Vincent":  lambda: build_humanoid(_tall_humanoid(1.04, 0.92)),   # tall, slim
    "Cid":      lambda: build_humanoid(_tall_humanoid(0.99, 1.10)),   # stocky
}


# ---------- driver ---------- #

def main() -> int:
    root = os.path.dirname(os.path.abspath(__file__))
    out_root = os.path.join(root, "meshes", "characters")
    requested = sys.argv[1:] or list(RECIPES.keys())
    for name in requested:
        builder = RECIPES.get(name)
        if builder is None:
            print(f"unknown recipe: {name}", file=sys.stderr)
            return 2
        mesh = builder()
        out_path = os.path.join(out_root, f"{name}.obj")
        mesh.write_obj(out_path, object_name=name)
        mn, mx = mesh.bounds()
        print(f"  {name}: {len(mesh.verts):4d} verts, {len(mesh.faces):4d} tris,"
              f" bounds X[{mn[0]:+.1f}, {mx[0]:+.1f}]"
              f" Y[{mn[1]:+.1f}, {mx[1]:+.1f}]"
              f" Z[{mn[2]:+.1f}, {mx[2]:+.1f}] -> {out_path}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
